### ISSUE TITLE
Convert to modular format using blueprints

### ISSUE THREAD

**Issue by ndiquattro** [ndiquattro/classqs#5]
Supposed to be more organized for larger flask projects:

https://www.digitalocean.com/community/tutorials/how-to-structure-large-flask-applications

**Comment by ndiquattro** [comment]
This is a better explanation/ example:
https://exploreflask.com/blueprints.html

**Comment by ghost** [comment]
Awesome, we should have a meeting where we figure this out because I also want to plan out what we need for each page so we can divide up the work. 

I think we can also put stuff like this in wiki in terms of what the "design" of the project is. Maybe you can design what the backend is going to look like and I can spell out the design of the web pages

**Comment by ndiquattro** [comment]
I just pushed a branch named 'reorg' that has it mostly reorganized. If you check it out /make client side work with it, we could probably merge it!
